export const REQUEST_RESULTS = 'REQUEST_RESULTS';
export const REQUEST_RESULTS_SUCCESS = 'REQUEST_RESULTS_SUCCESS';
export const REQUEST_RESULTS_ERROR = 'REQUEST_RESULTS_ERROR';
export const SET_FILTER_VALUE= 'SET_FILTER_VALUE';